### ISSUE TITLE
Mejorar el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-anniavdc#1]
Buen trabajo @anniavdc !!

Algunas pistas para acabarlo:

- [x] Añade un título a la página (Mi lista de Pokemons)
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Mueve el `li` fuera del componente 'Pokemon', de esta manera Pokemon es un componente con una tarjeta que podemos usar en diferentes sitios y no solo dentro de un `ul`
- [x] Elimina el código comentado
- [x] Apaña estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by anniavdc** [comment]
Hi @nasivuela ! I think the first ones are ready and also point 1 of the second improvements list.

**Comment by nasivuela** [comment]
Eso tiene muy buena pinta!
Como recomendación yo movería los archivos de estilos, para que estén junto a sus componentes ;)

![](https://media.giphy.com/media/cHPJPQawNjuPS/giphy.gif)
